import { Airport } from "../services/trips";

const airports: Airport[] = [
  {
    iataCode: "ACE",
    name: "Lanzarote Airport",
    cityName: "Lanzarote Island",
    countryName: "Spain",
    countryIsoCode: "ES",
    latitude: 28.948812,
    longitude: -13.606606,
  },
  {
    iataCode: "ADA",
    name: "Adana Şakirpaşa Airport",
    cityName: "Adana",
    countryName: "Turkey",
    countryIsoCode: "TR",
    latitude: 36.982185,
    longitude: 35.280393,
  },
  {
    iataCode: "ADB",
    name: "Adnan Menderes Airport",
    cityName: "Izmir",
    countryName: "Turkey",
    countryIsoCode: "TR",
    latitude: 38.293064,
    longitude: 27.153848,
  },
  {
    iataCode: "AER",
    name: "Sochi International Airport",
    cityName: "Sochi",
    countryName: "Russia",
    countryIsoCode: "RU",
    latitude: 43.449558,
    longitude: 39.951432,
  },
  {
    iataCode: "AGP",
    name: "Málaga Airport",
    cityName: "Málaga",
    countryName: "Spain",
    countryIsoCode: "ES",
    latitude: 36.674994,
    longitude: -4.495945,
  },
  {
    iataCode: "ALC",
    name: "Alicante-Elche Airport",
    cityName: "Alicante",
    countryName: "Spain",
    countryIsoCode: "ES",
    latitude: 38.283823,
    longitude: -0.557899,
  },
  {
    iataCode: "AMS",
    name: "Amsterdam Airport Schiphol",
    cityName: "Amsterdam",
    countryName: "Netherlands",
    countryIsoCode: "NL",
    latitude: 52.309323,
    longitude: 4.762518,
  },
  {
    iataCode: "ARN",
    name: "Stockholm Airport",
    cityName: "Stockholm",
    countryName: "Sweden",
    countryIsoCode: "SE",
    latitude: 59.65124,
    longitude: 17.926761,
  },
  {
    iataCode: "ATH",
    name: "Athens International Airport",
    cityName: "Athens",
    countryName: "Greece",
    countryIsoCode: "GR",
    latitude: 37.93637,
    longitude: 23.945152,
  },
  {
    iataCode: "ATL",
    name: "Atlanta International Airport",
    cityName: "Atlanta",
    countryName: "United States",
    countryIsoCode: "US",
    latitude: 33.639253,
    longitude: -84.431594,
  },
  {
    iataCode: "AYT",
    name: "Antalya Airport",
    cityName: "Antalya",
    countryName: "Turkey",
    countryIsoCode: "TR",
    latitude: 36.898904,
    longitude: 30.80077,
  },
  {
    iataCode: "BCN",
    name: "Barcelona Airport",
    cityName: "Barcelona",
    countryName: "Spain",
    countryIsoCode: "ES",
    latitude: 41.299069,
    longitude: 2.077617,
  },
  {
    iataCode: "BEG",
    name: "Belgrade Nikola Tesla Airport",
    cityName: "Belgrade",
    countryName: "Serbia",
    countryIsoCode: "RS",
    latitude: 44.818762,
    longitude: 20.308394,
  },
  {
    iataCode: "BFS",
    name: "Belfast International Airport",
    cityName: "Belfast",
    countryName: "United Kingdom",
    countryIsoCode: "GB",
    latitude: 54.659133,
    longitude: -6.216425,
  },
  {
    iataCode: "BGO",
    name: "Bergen Airport Flesland",
    cityName: "Bergen",
    countryName: "Norway",
    countryIsoCode: "NO",
    latitude: 60.291951,
    longitude: 5.221483,
  },
  {
    iataCode: "BGY",
    name: "Bergamo Airport",
    cityName: "Parma",
    countryName: "Italy",
    countryIsoCode: "IT",
    latitude: 45.671035,
    longitude: 9.702351,
  },
  {
    iataCode: "BHX",
    name: "Birmingham International Airport",
    cityName: "Birmingham",
    countryName: "United Kingdom",
    countryIsoCode: "GB",
    latitude: 52.453426,
    longitude: -1.743105,
  },
  {
    iataCode: "BIO",
    name: "Bilbao Airport",
    cityName: "Bilbao",
    countryName: "Spain",
    countryIsoCode: "ES",
    latitude: 43.302579,
    longitude: -2.909009,
  },
  {
    iataCode: "BLQ",
    name: "Bologna Guglielmo Marconi Airport",
    cityName: "Bologna",
    countryName: "Italy",
    countryIsoCode: "IT",
    latitude: 44.533369,
    longitude: 11.29022,
  },
  {
    iataCode: "BOD",
    name: "Bordeaux–Mérignac Airport",
    cityName: "Bordeaux",
    countryName: "France",
    countryIsoCode: "FR",
    latitude: 44.82922,
    longitude: -0.711095,
  },
  {
    iataCode: "BRS",
    name: "Bristol Airport",
    cityName: "Bristol",
    countryName: "United Kingdom",
    countryIsoCode: "GB",
    latitude: 51.384043,
    longitude: -2.71628,
  },
  {
    iataCode: "BRU",
    name: "Brussels National Airport",
    cityName: "Brussels",
    countryName: "Belgium",
    countryIsoCode: "BE",
    latitude: 50.899987,
    longitude: 4.484161,
  },
  {
    iataCode: "BSL",
    name: "EuroAirport Basel - Mulhouse - Freiburg Airport",
    cityName: "Basel",
    countryName: "Switzerland",
    countryIsoCode: "CH",
    latitude: 47.59,
    longitude: 7.5291667,
  },
  {
    iataCode: "BUD",
    name: "Budapest Ferenc Liszt International Airport",
    cityName: "Budapest",
    countryName: "Hungary",
    countryIsoCode: "HU",
    latitude: 47.433242,
    longitude: 19.259435,
  },
  {
    iataCode: "CAN",
    name: "Guangzhou Baiyun International Airport",
    cityName: "Guangzhou",
    countryName: "China",
    countryIsoCode: "CN",
    latitude: 23.390901,
    longitude: 113.298378,
  },
  {
    iataCode: "CDG",
    name: "Paris Charles de Gaulle Airport",
    cityName: "Paris",
    countryName: "France",
    countryIsoCode: "FR",
    latitude: 49.009592,
    longitude: 2.555675,
  },
  {
    iataCode: "CGN",
    name: "Cologne Bonn Airport",
    cityName: "Cologne",
    countryName: "Germany",
    countryIsoCode: "DE",
    latitude: 50.874401,
    longitude: 7.129296,
  },
  {
    iataCode: "CKG",
    name: "Chongqing Jiangbei International Airport",
    cityName: "Chongqing",
    countryName: "China",
    countryIsoCode: "CN",
    latitude: 29.719207,
    longitude: 106.641892,
  },
  {
    iataCode: "CLT",
    name: "Charlotte Douglas International Airport",
    cityName: "Charlotte",
    countryName: "United States",
    countryIsoCode: "US",
    latitude: 35.217956,
    longitude: -80.941021,
  },
  {
    iataCode: "CPH",
    name: "Kastrup Airport",
    cityName: "Roskilde",
    countryName: "Denmark",
    countryIsoCode: "DK",
    latitude: 55.621625,
    longitude: 12.653191,
  },
  {
    iataCode: "CRL",
    name: "Brussels South Charleroi Airport",
    cityName: "Brussels",
    countryName: "Belgium",
    countryIsoCode: "BE",
    latitude: 50.459203,
    longitude: 4.45382,
  },
  {
    iataCode: "CTA",
    name: "Catania–Fontanarossa Airport",
    cityName: "Catania",
    countryName: "Italy",
    countryIsoCode: "IT",
    latitude: 37.468081,
    longitude: 15.066226,
  },
  {
    iataCode: "CTU",
    name: "Chengdu Shuangliu International Airport",
    cityName: "Chengdu",
    countryName: "China",
    countryIsoCode: "CN",
    latitude: 30.579388,
    longitude: 103.950296,
  },
  {
    iataCode: "DEL",
    name: "Indira Gandhi International Airport",
    cityName: "Delhi",
    countryName: "India",
    countryIsoCode: "IN",
    latitude: 28.563054,
    longitude: 77.102051,
  },
  {
    iataCode: "DEN",
    name: "Denver International Airport",
    cityName: "Denver",
    countryName: "United States",
    countryIsoCode: "US",
    latitude: 39.85733,
    longitude: -104.673118,
  },
  {
    iataCode: "DFW",
    name: "Dallas/Fort Worth International Airport",
    cityName: "Dallas",
    countryName: "United States",
    countryIsoCode: "US",
    latitude: 32.896738,
    longitude: -97.03711,
  },
  {
    iataCode: "DME",
    name: "Domodedovo International Airport",
    cityName: "Moscow",
    countryName: "Russia",
    countryIsoCode: "RU",
    latitude: 55.412621,
    longitude: 37.901898,
  },
  {
    iataCode: "DOH",
    name: "Hamad International Airport",
    cityName: "Doha",
    countryName: "Qatar",
    countryIsoCode: "QA",
    latitude: 25.267718,
    longitude: 51.61069,
  },
  {
    iataCode: "DUB",
    name: "Dublin Airport",
    cityName: "Dublin",
    countryName: "Ireland",
    countryIsoCode: "IE",
    latitude: 53.423304,
    longitude: -6.261241,
  },
  {
    iataCode: "DUS",
    name: "Düsseldorf International Airport",
    cityName: "Duesseldorf",
    countryName: "Germany",
    countryIsoCode: "DE",
    latitude: 51.282829,
    longitude: 6.766503,
  },
  {
    iataCode: "EDI",
    name: "Edinburgh Airport",
    cityName: "Edinburgh",
    countryName: "United Kingdom",
    countryIsoCode: "GB",
    latitude: 55.949381,
    longitude: -3.369726,
  },
  {
    iataCode: "EIN",
    name: "Eindhoven Airport",
    cityName: "Eindhoven",
    countryName: "Netherlands",
    countryIsoCode: "NL",
    latitude: 51.452731,
    longitude: 5.380284,
  },
  {
    iataCode: "EMA",
    name: "Midlands East",
    cityName: "Nottingham",
    countryName: "United Kingdom",
    countryIsoCode: "GB",
    latitude: 52.829361,
    longitude: -1.328905,
  },
  {
    iataCode: "ESB",
    name: "Ankara Esenboğa International Airport",
    cityName: "Ankara",
    countryName: "Turkey",
    countryIsoCode: "TR",
    latitude: 40.123707,
    longitude: 32.994441,
  },
  {
    iataCode: "FAO",
    name: "Faro Airport",
    cityName: "Faro",
    countryName: "Portugal",
    countryIsoCode: "PT",
    latitude: 37.016492,
    longitude: -7.966788,
  },
  {
    iataCode: "FCO",
    name: "Rome Airport",
    cityName: "Rome",
    countryName: "Italy",
    countryIsoCode: "IT",
    latitude: 41.796131,
    longitude: 12.247275,
  },
  {
    iataCode: "FRA",
    name: "Frankfurt Airport",
    cityName: "Frankfurt",
    countryName: "Germany",
    countryIsoCode: "DE",
    latitude: 50.040962,
    longitude: 8.566754,
  },
  {
    iataCode: "FUE",
    name: "Fuerteventura Airport",
    cityName: "Fuerteventura Island",
    countryName: "Spain",
    countryIsoCode: "ES",
    latitude: 28.452008,
    longitude: -13.865818,
  },
  {
    iataCode: "GLA",
    name: "Glasgow International Airport",
    cityName: "Glasgow",
    countryName: "United Kingdom",
    countryIsoCode: "GB",
    latitude: 55.869351,
    longitude: -4.432634,
  },
  {
    iataCode: "GOT",
    name: "Gothenburg-Landvetter Airport",
    cityName: "Gothenburg",
    countryName: "Sweden",
    countryIsoCode: "SE",
    latitude: 57.665874,
    longitude: 12.288502,
  },
  {
    iataCode: "GVA",
    name: "Geneva International Airport",
    cityName: "Geneva",
    countryName: "Switzerland",
    countryIsoCode: "CH",
    latitude: 46.235097,
    longitude: 6.107978,
  },
  {
    iataCode: "HAJ",
    name: "Hannover-Langenhagen Airport",
    cityName: "Hanover",
    countryName: "Germany",
    countryIsoCode: "DE",
    latitude: 52.459975,
    longitude: 9.690845,
  },
  {
    iataCode: "HAM",
    name: "Hamburg Airport",
    cityName: "Hamburg",
    countryName: "Germany",
    countryIsoCode: "DE",
    latitude: 53.630691,
    longitude: 9.994291,
  },
  {
    iataCode: "HEL",
    name: "Helsinki Airport",
    cityName: "Helsinki",
    countryName: "Finland",
    countryIsoCode: "FI",
    latitude: 60.317458,
    longitude: 24.96436,
  },
  {
    iataCode: "HER",
    name: "Heraklion International Airport",
    cityName: "Heraklion",
    countryName: "Greece",
    countryIsoCode: "GR",
    latitude: 35.338466,
    longitude: 25.176541,
  },
  {
    iataCode: "HKG",
    name: "Hong Kong Airport",
    cityName: "Hong Kong",
    countryName: "Hong Kong",
    countryIsoCode: "HK",
    latitude: 22.313203,
    longitude: 113.928403,
  },
  {
    iataCode: "IAH",
    name: "Houston International Airport",
    cityName: "Houston",
    countryName: "United States",
    countryIsoCode: "US",
    latitude: 29.984868,
    longitude: -95.341173,
  },
  {
    iataCode: "IBZ",
    name: "Ibiza Airport",
    cityName: "Ibiza",
    countryName: "Spain",
    countryIsoCode: "ES",
    latitude: 38.874118,
    longitude: 1.371348,
  },
  {
    iataCode: "ICN",
    name: "Incheon International Airport",
    cityName: "Seoul",
    countryName: "South Korea",
    countryIsoCode: "KR",
    latitude: 37.455609,
    longitude: 126.45106,
  },
  {
    iataCode: "IST",
    name: "Istanbul Airport",
    cityName: "Istanbul",
    countryName: "Turkey",
    countryIsoCode: "TR",
    latitude: 41.261492,
    longitude: 28.742105,
  },
  {
    iataCode: "JFK",
    name: "John F. Kennedy International Airport",
    cityName: "New York City",
    countryName: "United States",
    countryIsoCode: "US",
    latitude: 40.640655,
    longitude: -73.781937,
  },
  {
    iataCode: "KBP",
    name: "Kiev International Airport",
    cityName: "Kyiv",
    countryName: "Ukraine",
    countryIsoCode: "UA",
    latitude: 50.343748,
    longitude: 30.894875,
  },
  {
    iataCode: "KEF",
    name: "Reykjavík-Keflavík Airport",
    cityName: "Reykjavík",
    countryName: "Iceland",
    countryIsoCode: "IS",
    latitude: 63.989256,
    longitude: -22.611812,
  },
  {
    iataCode: "KMG",
    name: "Kunming Changshui International Airport",
    cityName: "Kunming",
    countryName: "China",
    countryIsoCode: "CN",
    latitude: 25.102726,
    longitude: 102.934038,
  },
  {
    iataCode: "KRK",
    name: "Krakow International Airport",
    cityName: "Krakow",
    countryName: "Poland",
    countryIsoCode: "PL",
    latitude: 50.076454,
    longitude: 19.790038,
  },
  {
    iataCode: "LAS",
    name: "Las Vegas International Airport",
    cityName: "Las Vegas",
    countryName: "United States",
    countryIsoCode: "US",
    latitude: 36.082104,
    longitude: -115.150093,
  },
  {
    iataCode: "LAX",
    name: "Los Angeles International Airport",
    cityName: "Los Angeles",
    countryName: "United States",
    countryIsoCode: "US",
    latitude: 33.942803,
    longitude: -118.408415,
  },
  {
    iataCode: "LED",
    name: "Saint Petersburg Airport",
    cityName: "Saint Petersburg",
    countryName: "Russia",
    countryIsoCode: "RU",
    latitude: 59.800146,
    longitude: 30.265169,
  },
  {
    iataCode: "LGW",
    name: "London Gatwick Airport",
    cityName: "London",
    countryName: "United Kingdom",
    countryIsoCode: "GB",
    latitude: 51.151676,
    longitude: -0.181958,
  },
  {
    iataCode: "LHR",
    name: "Heathrow Airport",
    cityName: "London",
    countryName: "United Kingdom",
    countryIsoCode: "GB",
    latitude: 51.470451,
    longitude: -0.457332,
  },
  {
    iataCode: "LIN",
    name: "Linate Airport",
    cityName: "Parma",
    countryName: "Italy",
    countryIsoCode: "IT",
    latitude: 45.455622,
    longitude: 9.278472,
  },
  {
    iataCode: "LIS",
    name: "Lisbon Humberto Delgado Airport",
    cityName: "Lisbon",
    countryName: "Portugal",
    countryIsoCode: "PT",
    latitude: 38.777551,
    longitude: -9.133335,
  },
  {
    iataCode: "LPA",
    name: "Gran Canaria Airport",
    cityName: "Las Palmas de Gran Canaria",
    countryName: "Spain",
    countryIsoCode: "ES",
    latitude: 27.932063,
    longitude: -15.385939,
  },
  {
    iataCode: "LPL",
    name: "Liverpool John Lennon Airport",
    cityName: "Liverpool",
    countryName: "United Kingdom",
    countryIsoCode: "GB",
    latitude: 53.334848,
    longitude: -2.851542,
  },
  {
    iataCode: "LTN",
    name: "Luton Airport",
    cityName: "London",
    countryName: "United Kingdom",
    countryIsoCode: "GB",
    latitude: 51.876396,
    longitude: -0.370965,
  },
  {
    iataCode: "LYS",
    name: "Lyon–Saint Exupéry Airport",
    cityName: "Lyon",
    countryName: "France",
    countryIsoCode: "FR",
    latitude: 45.724457,
    longitude: 5.084092,
  },
  {
    iataCode: "MAD",
    name: "Adolfo Suárez Madrid–Barajas Airport",
    cityName: "Madrid",
    countryName: "Spain",
    countryIsoCode: "ES",
    latitude: 40.484669,
    longitude: -3.565533,
  },
  {
    iataCode: "MAN",
    name: "Ringway Airport",
    cityName: "Manchester",
    countryName: "United Kingdom",
    countryIsoCode: "GB",
    latitude: 53.356782,
    longitude: -2.274418,
  },
  {
    iataCode: "MCO",
    name: "Orlando International Airport",
    cityName: "Orlando",
    countryName: "United States",
    countryIsoCode: "US",
    latitude: 28.430869,
    longitude: -81.308326,
  },
  {
    iataCode: "MEX",
    name: "Mexico City International Airport",
    cityName: "Mexico City",
    countryName: "Mexico",
    countryIsoCode: "MX",
    latitude: 19.435959,
    longitude: -99.072325,
  },
  {
    iataCode: "MIA",
    name: "Miami International Airport",
    cityName: "Miami",
    countryName: "United States",
    countryIsoCode: "US",
    latitude: 25.79421,
    longitude: -80.286296,
  },
  {
    iataCode: "MLA",
    name: "Luqa Airport",
    cityName: "Valletta",
    countryName: "Malta",
    countryIsoCode: "MT",
    latitude: 35.854925,
    longitude: 14.483374,
  },
  {
    iataCode: "MRS",
    name: "Marseille Provence Airport",
    cityName: "Marseille",
    countryName: "France",
    countryIsoCode: "FR",
    latitude: 43.438871,
    longitude: 5.219057,
  },
  {
    iataCode: "MUC",
    name: "Munich International Airport",
    cityName: "Munich",
    countryName: "Germany",
    countryIsoCode: "DE",
    latitude: 48.353529,
    longitude: 11.787444,
  },
  {
    iataCode: "MXP",
    name: "Malpensa International Airport",
    cityName: "Parma",
    countryName: "Italy",
    countryIsoCode: "IT",
    latitude: 45.628515,
    longitude: 8.71852,
  },
  {
    iataCode: "NAP",
    name: "Naples International Airport",
    cityName: "Naples",
    countryName: "Italy",
    countryIsoCode: "IT",
    latitude: 40.886048,
    longitude: 14.291082,
  },
  {
    iataCode: "NCE",
    name: "Nice Côte d'Azur International Airport",
    cityName: "Nice",
    countryName: "France",
    countryIsoCode: "FR",
    latitude: 43.660536,
    longitude: 7.209657,
  },
  {
    iataCode: "NCL",
    name: "Newcastle Airport",
    cityName: "Newcastle",
    countryName: "United Kingdom",
    countryIsoCode: "GB",
    latitude: 55.037354,
    longitude: -1.69799,
  },
  {
    iataCode: "NRT",
    name: "Narita International Airport",
    cityName: "Tokyo",
    countryName: "Japan",
    countryIsoCode: "JP",
    latitude: 35.767545,
    longitude: 140.386612,
  },
  {
    iataCode: "NTE",
    name: "Nantes Atlantique Airport",
    cityName: "Nantes",
    countryName: "France",
    countryIsoCode: "FR",
    latitude: 47.15467,
    longitude: -1.607618,
  },
  {
    iataCode: "OPO",
    name: "Francisco de Sá Carneiro Airport",
    cityName: "Porto",
    countryName: "Portugal",
    countryIsoCode: "PT",
    latitude: 41.244645,
    longitude: -8.677684,
  },
  {
    iataCode: "ORD",
    name: "Chicago O'Hare International Airport",
    cityName: "Chicago",
    countryName: "United States",
    countryIsoCode: "US",
    latitude: 41.978367,
    longitude: -87.904712,
  },
  {
    iataCode: "OSL",
    name: "Oslo Airport",
    cityName: "Oslo",
    countryName: "Norway",
    countryIsoCode: "NO",
    latitude: 60.194004,
    longitude: 11.10039,
  },
  {
    iataCode: "OTP",
    name: "Bucharest - Henri Coandă International Airport",
    cityName: "Bucharest",
    countryName: "Romania",
    countryIsoCode: "RO",
    latitude: 44.571476,
    longitude: 26.088081,
  },
  {
    iataCode: "PEK",
    name: "Beijing Capital International Airport",
    cityName: "Beijing",
    countryName: "China",
    countryIsoCode: "CN",
    latitude: 40.079583,
    longitude: 116.585551,
  },
  {
    iataCode: "PHX",
    name: "Phoenix Airport",
    cityName: "Phoenix",
    countryName: "United States",
    countryIsoCode: "US",
    latitude: 33.434948,
    longitude: -112.003412,
  },
  {
    iataCode: "PMI",
    name: "Palma de Mallorca Airport",
    cityName: "Palma",
    countryName: "Spain",
    countryIsoCode: "ES",
    latitude: 39.549785,
    longitude: 2.734176,
  },
  {
    iataCode: "PMO",
    name: "Palermo Airport",
    cityName: "Palermo",
    countryName: "Italy",
    countryIsoCode: "IT",
    latitude: 38.179495,
    longitude: 13.095599,
  },
  {
    iataCode: "PRG",
    name: "Prague Ruzyně International Airport",
    cityName: "Prague",
    countryName: "Czechia",
    countryIsoCode: "CZ",
    latitude: 50.102606,
    longitude: 14.262213,
  },
  {
    iataCode: "PSA",
    name: "Pisa International Airport",
    cityName: "Pisa",
    countryName: "Italy",
    countryIsoCode: "IT",
    latitude: 43.688844,
    longitude: 10.395121,
  },
  {
    iataCode: "PVG",
    name: "Shanghai Pudong International Airport",
    cityName: "Shanghai",
    countryName: "China",
    countryIsoCode: "CN",
    latitude: 31.146201,
    longitude: 121.803339,
  },
  {
    iataCode: "RHO",
    name: "Rhodes International Airport",
    cityName: "Rhodes",
    countryName: "Greece",
    countryIsoCode: "GR",
    latitude: 36.404228,
    longitude: 28.087689,
  },
  {
    iataCode: "RIX",
    name: "Riga International Airport",
    cityName: "Riga",
    countryName: "Latvia",
    countryIsoCode: "LV",
    latitude: 56.923096,
    longitude: 23.974005,
  },
  {
    iataCode: "SAW",
    name: "Sabiha Gökçen International Airport",
    cityName: "Istanbul",
    countryName: "Turkey",
    countryIsoCode: "TR",
    latitude: 40.900629,
    longitude: 29.309186,
  },
  {
    iataCode: "SEA",
    name: "Seattle–Tacoma International Airport",
    cityName: "Seattle",
    countryName: "United States",
    countryIsoCode: "US",
    latitude: 47.447277,
    longitude: -122.306673,
  },
  {
    iataCode: "SHA",
    name: "Shanghai Hongqiao International Airport",
    cityName: "Shanghai",
    countryName: "China",
    countryIsoCode: "CN",
    latitude: 31.197854,
    longitude: 121.335264,
  },
  {
    iataCode: "SIP",
    name: "Simferopol International Airport",
    cityName: "Simferopol",
    countryName: "Ukraine",
    countryIsoCode: "UA",
    latitude: 45.041693,
    longitude: 33.982814,
  },
  {
    iataCode: "SKG",
    name: "Thessaloniki International Airport",
    cityName: "Thessaloniki",
    countryName: "Greece",
    countryIsoCode: "GR",
    latitude: 40.520087,
    longitude: 22.971357,
  },
  {
    iataCode: "SOF",
    name: "Sofia Airport",
    cityName: "Sofia",
    countryName: "Bulgaria",
    countryIsoCode: "BG",
    latitude: 42.693408,
    longitude: 23.410679,
  },
  {
    iataCode: "STN",
    name: "London Stansted Airport",
    cityName: "London",
    countryName: "United Kingdom",
    countryIsoCode: "GB",
    latitude: 51.886422,
    longitude: 0.244234,
  },
  {
    iataCode: "STR",
    name: "Stuttgart Airport",
    cityName: "Stuttgart",
    countryName: "Germany",
    countryIsoCode: "DE",
    latitude: 48.690324,
    longitude: 9.203598,
  },
  {
    iataCode: "SVO",
    name: "Moscow International Airport",
    cityName: "Moscow",
    countryName: "Russia",
    countryIsoCode: "RU",
    latitude: 55.970288,
    longitude: 37.415021,
  },
  {
    iataCode: "SVQ",
    name: "San Pablo Airport",
    cityName: "Seville",
    countryName: "Spain",
    countryIsoCode: "ES",
    latitude: 37.419825,
    longitude: -5.895452,
  },
  {
    iataCode: "SZX",
    name: "Shenzhen Bao'an International Airport",
    cityName: "Shenzhen",
    countryName: "China",
    countryIsoCode: "CN",
    latitude: 22.639334,
    longitude: 113.81083,
  },
  {
    iataCode: "TFS",
    name: "Tenerife South-Reina Sofia Airport",
    cityName: "Santa Cruz de Tenerife",
    countryName: "Spain",
    countryIsoCode: "ES",
    latitude: 28.044471,
    longitude: -16.572497,
  },
  {
    iataCode: "TLS",
    name: "Toulouse-Blagnac Airport",
    cityName: "Toulouse",
    countryName: "France",
    countryIsoCode: "FR",
    latitude: 43.629417,
    longitude: 1.36732,
  },
  {
    iataCode: "TPE",
    name: "Taiwan Taoyuan International Airport",
    cityName: "Taipei",
    countryName: "Taiwan",
    countryIsoCode: "TW",
    latitude: 25.076981,
    longitude: 121.232767,
  },
  {
    iataCode: "BER",
    name: "Berlin",
    cityName: "Berlin",
    countryName: "Germany",
    countryIsoCode: "DE",
    latitude: 52.55970001,
    longitude: 13.2876997,
  },
  {
    iataCode: "VCE",
    name: "Venice Marco Polo Airport",
    cityName: "Venice",
    countryName: "Italy",
    countryIsoCode: "IT",
    latitude: 45.504151,
    longitude: 12.343742,
  },
  {
    iataCode: "VIE",
    name: "Vienna International Airport",
    cityName: "Vienna",
    countryName: "Austria",
    countryIsoCode: "AT",
    latitude: 48.117373,
    longitude: 16.563598,
  },
  {
    iataCode: "VKO",
    name: "Vnukovo International Airport",
    cityName: "Moscow",
    countryName: "Russia",
    countryIsoCode: "RU",
    latitude: 55.595394,
    longitude: 37.271694,
  },
  {
    iataCode: "VLC",
    name: "Valencia Airport",
    cityName: "Valencia",
    countryName: "Spain",
    countryIsoCode: "ES",
    latitude: 39.490134,
    longitude: -0.47891,
  },
  {
    iataCode: "WAW",
    name: "Warsaw Chopin Airport",
    cityName: "Warsaw",
    countryName: "Poland",
    countryIsoCode: "PL",
    latitude: 52.167452,
    longitude: 20.96917,
  },
  {
    iataCode: "ZRH",
    name: "Zurich Airport",
    cityName: "Zurich",
    countryName: "Switzerland",
    countryIsoCode: "CH",
    latitude: 47.453767,
    longitude: 8.556768,
  },
];

export default airports;
